back/config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  root 'home#index'

  get 'welcome-extension', to: 'home#extension_install_hook'
  get 'download-bettermask', to: 'home#download_bettermask'
  get 'coming-soon/:platform', to: 'home#coming_soon'
  get 'detect-web3', to: 'home#detect_web3'

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'me', to: 'sessions#me'
  get 'logout', to: 'sessions#destroy'
  get 'extension-oauth-callback', to: 'sessions#extension_oauth_callback'


  #
  # REFERRALS
  #

  get 'r/:referral_code/:app_slug', to: 'referrals#show', as: :referral_link
  get 'r/:referral_code/:app_slug/:source', to: 'referrals#show', as: :referral_link_with_source

  resources :referrals, only: [:create] do
    collection do
      get 'post_auth_hook', to: 'referrals#post_auth_hook'
    end
  end

  resources :referral_tokens, only: [] do
    collection do
      post 'claim'
    end
  end

  get 'admin', to: 'admin#index'

  namespace :api do
    resources :apps, only: [:index]
    resources :referrals, only: [:index] do
      collection do
        post :convert
      end
    end
    resources :vaults, only: [:index, :create] do
      collection do
        get :unlock
        get :wallet_address
      end
    end

    resources :coin_rewards, only: [] do
      collection do
        post :mint
      end
    end

    get '/me', to: 'users#me'
    get '/referral-links', to: 'users#referral_links'
    get '/offers', to: 'users#offers'
  end
end

back/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def extension_install_hook
  end

  def download_bettermask
  end

  def coming_soon
    case params['platform']
      when 'android'
        platform = 'Android'
      when 'ios'
        platform = 'iOS'
      else
        platform = 'mobile'
    end

    render template: 'home/coming_soon', locals: {platform: platform}
  end

  def detect_web3
    response.headers['X-FRAME-OPTIONS'] = 'ALLOWALL'
  end
end

back/app/helpers/home_helper.rb
module HomeHelper
end

back/app/views/home/coming_soon.html.erb
<style>
  #root {
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
  }
</style>

<div id="root">
  <h2>Our <%= platform %> application is coming soon! We'll keep you posted when it goes live!</h2>
</div>

back/app/views/home/detect_web3.html.erb
<script type="text/javascript" charset="utf-8">
  function reportToExtension(web3Detected) {
    var params = {
      web3Detected: web3Detected,
    };

    var data = { type: "bettermask__web3-detection-result", params: params };
    window.postMessage(data, '<%= root_url %>');
  }

  window.addEventListener('load', function() {
    console.log('window load event fired');
    // Checking if Web3 has been injected by the browser (Mist/MetaMask)
    var web3Detected = typeof web3 !== 'undefined';
    reportToExtension(web3Detected);
  });
</script>

back/app/views/home/download_bettermask.html.erb
<style>
  #root {
    max-width: 1024px;
    margin: 0 auto;
    text-align: center;
    height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }

  #root h1 {
    text-align: center;
  }

  .flex-row {
    display: flex;
    flex-direction: row;
    justify-content: center;
  }

  .flex-col {
    width: 200px;
    padding: 0 32px;
  }

  input#referral-link {
    font-size: 1.6em;
    padding: 8px;
    border: 1px solid lightgray;
  }

  button#copy-button {
    font-size: 1.6em;
    padding: 8px;
    border: 1px solid #8363d4;
    background: #8363d4;
    color: white;
  }

  a.flat-link {
    text-decoration: inherit;
    color: inherit;
  }

  a.flat-link:hover {
    text-decoration: inherit;
    color: inherit;
  }
</style>

<div id="hidden-root" style="display: none">
  <div id="root">
    <h1>Install Bettermask to continue</h1>

    <p>
      Bettermask is a <strong>simple</strong> and <strong>secure
      crypto-assets wallet</strong>.
    </p>


    <div>
      <%= image_tag 'download_bettermask/chrome-logo.svg', style: 'width: 180px' %>
    </div>
    <h2 style="margin-bottom: 0">Chrome extension</h2>
    <p>Open the following link in Chrome to install the extension:</p>
    <div>
      <input id="referral-link" type="text" readonly value="<%= session[:referral_link] %>" /><button id="copy-button">Copy Link</button>
    </div>
    <div style="margin-bottom: 64px">
      <span>&nbsp;</span>
      <span id="copy-confirm" style="display: none">Copied!</span>
      <span>&nbsp;</span>
    </div>

    <h2>Other options</h2>

    <div class="flex-row">
      <div class="flex-col">
        <a class="flat-link" href="/coming-soon/android">
          <div class="icon">
            <%= image_tag 'download_bettermask/google_play_store.png', style: 'width: 100%' %>
          </div>
          <div>
            <h3>Android app</h3>
          </div>
        </a>
      </div>

      <div class="flex-col">
        <a class="flat-link" href="/coming-soon/ios">
          <div class="icon">
            <%= image_tag 'download_bettermask/ios_app_store.png', style: 'width: 100%' %>
          </div>
          <div>
            <h3>iOS app</h3>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  function attachCopyHandler() {
    var btn = document.getElementById('copy-button');
    var link = document.getElementById('referral-link');
    var confirm = document.getElementById('copy-confirm');
    btn.addEventListener('click', function () {
      link.select();
      /* Copy the text inside the text field */
      document.execCommand("copy");

      confirm.style.display = 'inline';
      setTimeout(function() {
        confirm.style.display = 'none';
      }, 1000)
    })
  }

  function isChrome() {
    try {
      window.chrome.runtime.sendMessage;
      return true;
    } catch(er) {
      return false;
    }
  }

  function isAndroid() {
    // https://stackoverflow.com/questions/6031412/detect-android-phone-via-javascript-jquery
    var ua = navigator.userAgent.toLowerCase();
    return ua.indexOf("android") > -1; // && ua.indexOf("mobile"); // ???
  }

  function isIPhone() {
    var ua = navigator.userAgent.toLowerCase();
    return ua.indexOf("iphone") > -1; // && ua.indexOf("mobile"); // ???
  }

  function redirect() {
    var chromeUrl = 'https://chrome.google.com/webstore/detail/example';

    if (isChrome()) {
      window.location.href = chromeUrl;
      return;
    }

    if (isAndroid()) {
      window.location.href = '/coming-soon/android';
      return;
    }

    if (isIPhone()) {
      window.location.href = '/coming-soon/ios';
      return;
    }

    document.getElementById('hidden-root').style.display = 'block';
  }

  window.history.replaceState({}, 'Install Bettermask', '<%= session[:referral_link] %>');

  attachCopyHandler();
  redirect();
</script>

back/app/views/home/extension_install_hook.html.erb
<style>
  div {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }

  #wrapper {
    width: 100vw;
    height: 100vh;
    padding: 64px;
    padding-top: 4px;
    padding-right: 32px;
    display: flex;
    flex-direction: row;
    justify-content: flex-end
  }

  #logo {
    width: 100px;
  }

  .welcome {
    font-size: 1.5em;
  }
</style>

<div id="wrapper">
  <div style="margin-right: 32px; text-align: center; padding-top: 100px">
    <% if params[:signedin].present? && @current_user.present? %>
      <p class="welcome">Welcome, <%= @current_user.first_name || @current_user.name %>!</p>
    <% end %>
    <h1>
      Click this icon
      <%= image_tag 'click_logo_inline.png', style: 'display: inline; vertical-align: middle' %>

      <% if params[:signedin].present? %>
        once again
        <br>
        to view your assets
      <% else %>
        <br>
        to open your vault
      <% end %>
    </h1>
  </div>

  <div>
    <%= image_tag 'arrow.png' %>
  </div>
</div>

back/app/views/home/index.html.erb
<h1>Home</h1>
<% if @current_user.present? %>
  <p><%= @current_user.name %></p>
  <a href="<%= logout_url %>">Logout</a>
<% else %>
  <p>Not authenticated</p>
  <a href="/auth/facebook">Sign in</a>
<% end %>

<div style="margin-top: 32px">
  <a href="#" id="wipe-local-storage">Wipe localStorage</a>
</div>

<script type="text/javascript" charset="utf-8">
  document.getElementById('wipe-local-storage').addEventListener('click', function (e) {
    e.preventDefault();

    localStorage.clear();
  })
</script>